name: Build Tauri (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # 不開 cache：你的 repo 目前沒有 lock 檔

      - name: Install dependencies (no lockfile)
        run: npm install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 安裝 NSIS 並將 NSIS 放進 PATH
      - name: Install NSIS (for .exe)
        run: choco install nsis --no-progress -y

      - name: Add NSIS to PATH
        run: echo "C:\Program Files (x86)\NSIS" >> $env:GITHUB_PATH

      - name: Verify NSIS
        run: |
          where makensis
          makensis /VERSION

      - name: Install Tauri CLI
        run: npm i -D @tauri-apps/cli

      - name: Show Tauri info
        run: npx tauri info

      # 只打包 NSIS，確保有 .exe 產出
      - name: Build (Tauri → NSIS .exe)
        env:
          RUST_BACKTRACE: 1
        run: npm run tauri:build -- --verbose

      - name: List possible outputs (debug)
        run: |
          echo "=== src-tauri/target (if exists) ==="
          if (Test-Path src-tauri/target) { Get-ChildItem -Recurse src-tauri/target | Select-Object FullName }
          echo "=== target (if exists) ==="
          if (Test-Path target) { Get-ChildItem -Recurse target | Select-Object FullName }

      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundles
          path: |
            src-tauri/target/**/bundle/**/*
            target/**/bundle/**/*
